In [10]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np


# 5.1 Introduction to pandas Data Structures

### Series

In [3]:
obj = pd.Series([4, 7, -5, 3])

created a Series

In [19]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

In [11]:
obj.values

array([ 4,  7, -5,  3])

gives you value is Series

In [12]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

gives you index in Series

In [56]:
obj2 = pd.Series([4,7,-5,3]); index = ['d', 'b', 'a','c']



index identified for each value

In [57]:
obj2

0    4
1    7
2   -5
3    3
dtype: int64

In [31]:
obj2.index



RangeIndex(start=0, stop=4, step=1)

"""different output"""

In [ ]:
obj2['a']


In [37]:
obj2['d'] = 6

In [ ]:
obj2[['c', 'a', 'd']]

In [45]:
obj2[obj2 > 0]


0    4
1    7
3    3
d    6
dtype: int64

In [46]:
obj * 2

0     8
1    14
2   -10
3     6
d    12
dtype: int64

In [ ]:
np.exp(obj2)

In [ ]:
'b' in obj2

False

In [ ]:
'e' in obj2

False

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}


In [ ]:
obj3 = pd.Series(sdata)

In [ ]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [ ]:
obj4 = pd.Series(sdata, index = states)


In [ ]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

pulled indexes from obj3 and placed in obj4

In [ ]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

Series as instances

In [ ]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [ ]:
obj4.name = 'population'

In [ ]:
obj4.index.name = 'state'

In [ ]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

added 'state' as index name and named it with 'population'

In [ ]:
obj

0    4
1    7
2   -5
3    3
d    6
dtype: int64

In [ ]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

altered Series's Index

### DataFrame

In [71]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [72]:
frame = pd.DataFrame(data)

In [73]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [74]:
pd.DataFrame(data, columns=['year', 'state', 'pop',])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

columns arranged

In [76]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], 
                        index=['one', 'two', 'three', 'four', 'five', 'six'])

In [77]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

no value in debt column and index modified

In [78]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [80]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [81]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

naming as 'three' (also modified index), retrieved by location

In [83]:
frame2['debt'] = 16.5

In [84]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [ ]:
frame2['debt'] = np.arange(6.)

In [90]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [91]:
frame2['debt'] = val

In [92]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

labels alligned to index and missing value inserted

In [93]:
frame2['eastern'] = frame2.state == 'Ohio'

In [94]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

new column "eastern" added as boolean

In [95]:
del frame2['eastern']

In [96]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [99]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [100]:
frame3 = pd.DataFrame(pop)


In [101]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

if nested dictionary passed, outer dictionary keys as columns and inner kets as row indices

In [102]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

transposed

In [103]:
pd.DataFrame(pop, index =[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

for specified index, blank value

In [104]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [105]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [106]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [107]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

column and index named


In [108]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [109]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [111]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [112]:
index = obj.index

In [113]:
obj

a    0
b    1
c    2
dtype: int64

In [114]:
index

Index(['a', 'b', 'c'], dtype='object')

In [115]:
index[1:]

Index(['b', 'c'], dtype='object')

In [117]:
index[1] = 'd'

TypeError: Index does not support mutable operations